# Generated by Django 6.0 on 2025-12-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(max_length=16)),
                ("external_fill_id", models.CharField(max_length=128, unique=True)),
                ("symbol", models.CharField(max_length=32)),
                ("side", models.CharField(max_length=8)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("notional", models.DecimalField(decimal_places=2, max_digits=20)),
                ("filled_at", models.DateTimeField()),
                ("raw", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="funds.fund"
                    ),
                ),
            ],
        ),
    ]
