# Generated by Django 6.0 on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountbrokercredential"),
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradefill",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.clientcapitalaccount",
            ),
        ),
        migrations.AlterField(
            model_name="tradefill",
            name="external_fill_id",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="tradefill",
            constraint=models.UniqueConstraint(
                fields=("account", "external_fill_id"),
                name="uq_tradefill_account_external_fill_id",
            ),
        ),
    ]
