# Generated by Django 6.0 on 2025-12-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("MGMT_FEE", "Management Fee")], max_length=32
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="funds.fund"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fund", "expense_type", "as_of_date"),
                        name="uq_fundexpense_fund_type_date",
                    )
                ],
            },
        ),
    ]
