# Generated by Django 6.0 on 2025-12-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of_month",
                    models.DateField(help_text="Month end date (YYYY-MM-last_day)"),
                ),
                (
                    "nav_bom",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="NAV at beginning of month",
                        max_digits=18,
                    ),
                ),
                (
                    "nav_eom",
                    models.DecimalField(
                        decimal_places=8, help_text="NAV at end of month", max_digits=18
                    ),
                ),
                (
                    "aum_eom",
                    models.DecimalField(
                        decimal_places=2, help_text="AUM at month end", max_digits=20
                    ),
                ),
                (
                    "fund_return",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Fund return for the month (decimal, e.g. 0.0234)",
                        max_digits=10,
                    ),
                ),
                ("benchmark_symbol", models.CharField(default="SPY", max_length=16)),
                (
                    "benchmark_return",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Benchmark return for same period",
                        max_digits=10,
                    ),
                ),
                (
                    "excess_return",
                    models.DecimalField(
                        decimal_places=6, help_text="Fund - benchmark", max_digits=10
                    ),
                ),
                (
                    "strategy_version",
                    models.CharField(
                        help_text="Strategy version hash or tag", max_length=64
                    ),
                ),
                (
                    "model_change",
                    models.BooleanField(
                        default=False,
                        help_text="True if model/logic changed this month",
                    ),
                ),
                (
                    "metrics_json",
                    models.JSONField(
                        default=dict,
                        help_text="Drawdown, volatility, Sharpe, exposure stats, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_snapshots",
                        to="funds.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of_month"],
                "indexes": [
                    models.Index(
                        fields=["fund", "as_of_month"],
                        name="performance_fund_id_f99207_idx",
                    )
                ],
                "unique_together": {("fund", "as_of_month")},
            },
        ),
        migrations.CreateModel(
            name="NAVSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Valuation date")),
                (
                    "nav_per_unit",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="NAV per unit on this date",
                        max_digits=18,
                    ),
                ),
                (
                    "total_units",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total outstanding units",
                        max_digits=20,
                    ),
                ),
                (
                    "aum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Assets under management (USD)",
                        max_digits=20,
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: broker cash balance",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "gross_exposure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "net_exposure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_snapshots",
                        to="funds.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["fund", "date"], name="performance_fund_id_2b8bbe_idx"
                    )
                ],
                "unique_together": {("fund", "date")},
            },
        ),
    ]
