# Generated by Django 6.0 on 2025-12-25 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of_month",
                    models.DateField(
                        help_text="Use the last calendar day of the month"
                    ),
                ),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "mtd_return",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Decimal return (e.g., 0.0123)",
                        max_digits=8,
                    ),
                ),
                ("ytd_return", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Max drawdown since inception",
                        max_digits=8,
                    ),
                ),
                (
                    "volatility",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Annualized volatility",
                        max_digits=8,
                    ),
                ),
                ("strategy_version", models.CharField(default="v1.0", max_length=64)),
                (
                    "metrics_json",
                    models.JSONField(
                        blank=True,
                        help_text="Frozen metrics used for tear sheet",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "as_of_month"],
                        name="performance_account_1ac2b6_idx",
                    )
                ],
                "unique_together": {("account", "as_of_month")},
            },
        ),
    ]
