# Generated by Django 6.0 on 2025-12-27 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("nav_start", models.DecimalField(decimal_places=8, max_digits=18)),
                ("nav_end", models.DecimalField(decimal_places=8, max_digits=18)),
                ("fund_return", models.DecimalField(decimal_places=10, max_digits=18)),
                (
                    "spy_return",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=18, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=18, null=True
                    ),
                ),
                (
                    "mgmt_fee_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("commentary", models.TextField(blank=True, null=True)),
                (
                    "html_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/html/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/pdf/"
                    ),
                ),
                (
                    "chart_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/charts/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_reports",
                        to="funds.fund",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-month", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fund", "year", "month"),
                        name="uq_monthly_report_fund_year_month",
                    )
                ],
            },
        ),
    ]
