# Generated by Django 6.0 on 2025-12-27 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_monthlyreportartifact"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monthlyreportartifact",
            name="uq_monthly_report_fund_year_month",
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="as_of_month",
            field=models.DateField(help_text="Month-end date (YYYY-MM-last_day)"),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="aum_eom",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Assets under management at month end",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="benchmark_return",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Benchmark return for same period",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="excess_return",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Fund minus benchmark return",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="model_change",
            field=models.BooleanField(
                default=False,
                help_text="True if model or allocation logic changed this month",
            ),
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="strategy_version",
            field=models.CharField(
                help_text="Strategy version, git hash, or tag", max_length=64
            ),
        ),
        migrations.DeleteModel(
            name="MonthlyReportArtifact",
        ),
    ]
