# Generated by Django 6.0 on 2025-12-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("SUB", "Subscription"), ("RED", "Redemption")],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("nav_at_flow", models.DecimalField(decimal_places=8, max_digits=18)),
                ("units_delta", models.DecimalField(decimal_places=8, max_digits=20)),
                ("flow_date", models.DateField()),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="funds.fund"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fund", "flow_date"],
                        name="accounts_ca_fund_id_f5a939_idx",
                    ),
                    models.Index(
                        fields=["client", "flow_date"],
                        name="accounts_ca_client__4266ec_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientCapitalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.DecimalField(decimal_places=8, max_digits=20)),
                ("nav_per_unit", models.DecimalField(decimal_places=8, max_digits=18)),
                ("last_valuation_date", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="funds.fund"
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "fund")},
            },
        ),
    ]
