# Generated by Django 6.0 on 2025-12-25 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custodian",
                    models.CharField(
                        choices=[
                            ("ALPACA", "Alpaca"),
                            ("IBKR", "Interactive Brokers"),
                            ("OTHER", "Other"),
                        ],
                        default="ALPACA",
                        max_length=20,
                    ),
                ),
                (
                    "custodian_account_masked",
                    models.CharField(
                        help_text="Masked account identifier (e.g., last 4 digits)",
                        max_length=32,
                    ),
                ),
                ("base_currency", models.CharField(default="USD", max_length=10)),
                (
                    "strategy_code",
                    models.CharField(default="ETF_WKLY_V1", max_length=64),
                ),
                ("opened_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("custodian", "custodian_account_masked")},
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_date", models.DateField()),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("fee", "Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
