# Generated by Django 6.0 on 2025-12-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clients", "0001_initial"),
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="capitalflow",
            name="accounts_ca_fund_id_f5a939_idx",
        ),
        migrations.RemoveIndex(
            model_name="capitalflow",
            name="accounts_ca_client__4266ec_idx",
        ),
        migrations.AlterField(
            model_name="capitalflow",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("SUB", "Subscription (Deposit)"),
                    ("RED", "Redemption (Withdraw)"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalflow",
            constraint=models.UniqueConstraint(
                fields=("fund", "client", "external_ref"),
                name="uq_capitalflow_fund_client_external_ref",
            ),
        ),
    ]
