# Generated by Django 6.0 on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_accountbrokercredential_environment"),
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPortfolioHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("ALPACA", "Alpaca"), ("IBKR", "Interactive Brokers")],
                        max_length=16,
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("as_of_datetime", models.DateTimeField()),
                ("timeframe", models.CharField(default="1D", max_length=16)),
                ("equity", models.DecimalField(decimal_places=2, max_digits=20)),
                ("profit_loss", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "profit_loss_pct",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "base_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_history",
                        to="accounts.clientcapitalaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["account_id", "-as_of_datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountportfoliohistory",
            constraint=models.UniqueConstraint(
                fields=("account", "as_of_datetime", "timeframe"),
                name="uq_acct_portfolio_history_account_dt_timeframe",
            ),
        ),
        migrations.AddIndex(
            model_name="accountportfoliohistory",
            index=models.Index(
                fields=["account", "as_of_date"],
                name="accounts_ac_account_88f37c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountportfoliohistory",
            index=models.Index(
                fields=["account", "timeframe"],
                name="accounts_ac_account_1098ad_idx",
            ),
        ),
    ]
