"""
Django settings for operations project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import datetime as dt
import os
from pathlib import Path

import dj_database_url

# from celery.schedules import crontab
from configurations import Configuration, values
from dotenv import load_dotenv
from patches.django_ses_linesep_patch import apply_django_ses_linesep_patch

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = os.path.join(BASE_DIR, ".env")
load_dotenv(dotenv_path)


apply_django_ses_linesep_patch()


class Common(Configuration):
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.Value("secret key", environ_prefix=None)

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = values.BooleanValue(False, environ_prefix=None)

    ALLOWED_HOSTS = values.ListValue([], environ_prefix=None)

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django.contrib.humanize",
        "admincolors",
        "funds",
        "trading",
        "clients",
        "accounts",
        "performance",
        "reporting",
        "fees",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ADMIN_COLORS = [("Portfolio-Operations", "css/admin.css")]

    ROOT_URLCONF = "core.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [os.path.join(BASE_DIR, "templates")],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "admincolors.context_processors.admin_theme",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "core.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

    DATABASES = {
        "default": dj_database_url.config(
            # Feel free to alter this value to suit your needs.
            default="sqlite:///operations.db",
            conn_max_age=600,
        )
    }

    # Password validation
    # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/6.0/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/6.0/howto/static-files/

    # celery configuration
    CELERY_BROKER_URL = values.Value("", environ_prefix=None)
    CELERY_ACCEPT_CONTENT = ["application/json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = "America/Denver"

    CELERY_BEAT_SCHEDULE = {
        "hello_task": {
            "task": "accounts.tasks.hello",
            "schedule": dt.timedelta(seconds=60),
        },
    }

    EMAIL_FROM = values.Value("email@test.com", environ_prefix=None)
    USE_SES_EMAIL = values.BooleanValue(False, environ_prefix=None)
    AWS_SES_USE_V2 = values.BooleanValue(False, environ_prefix=None)
    AWS_SES_ACCESS_KEY_ID = values.Value("", environ_prefix=None)
    AWS_SES_SECRET_ACCESS_KEY = values.Value("", environ_prefix=None)

    USE_S3_STORAGE = values.BooleanValue(False, environ_prefix=None)
    AWS_DEFAULT_ACL = "public-read"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

    AWS_QUERYSTRING_AUTH = False
    AWS_STORAGE_BUCKET_NAME = values.Value("", environ_prefix=None)
    AWS_S3_ACCESS_KEY_ID = values.Value("", environ_prefix=None)
    AWS_S3_ENDPOINT_URL = values.Value("", environ_prefix=None)
    AWS_S3_SECRET_ACCESS_KEY = values.Value("", environ_prefix=None)
    AWS_LOCATION = values.Value("static", environ_prefix=None)
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    @property
    def STORAGES(self):
        if self.USE_S3_STORAGE:

            return {
                "default": {
                    "BACKEND": "apps.common.storages.MediaStorage",
                    "OPTIONS": {},
                },
                "staticfiles": {
                    "BACKEND": "apps.common.storages.StaticStorage",
                },
            }

        return {
            "default": {
                "BACKEND": "django.core.files.storage.FileSystemStorage",
            },
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
            },
        }

    @property
    def STATIC_URL(self):
        if self.USE_S3_STORAGE:
            return f"{self.AWS_S3_ENDPOINT_URL}/{self.AWS_LOCATION}/"

        return "/static/"

    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "assets"),
    ]

    @property
    def STATIC_ROOT(self):
        if not self.USE_S3_STORAGE:
            return os.path.join(BASE_DIR, "static")
        return ""

    @property
    def MEDIA_URL(self):
        if self.USE_S3_STORAGE:

            return f"{self.AWS_S3_ENDPOINT_URL}/{self.PUBLIC_MEDIA_LOCATION}/"

        return "/media/"

    @property
    def MEDIA_ROOT(self):
        if not self.USE_S3_STORAGE:
            return os.path.join(BASE_DIR, "media")
        return ""

    @property
    def EMAIL_BACKEND(self):

        if self.USE_SES_EMAIL:
            return "django_ses.SESBackend"

        return "django.core.mail.backends.console.EmailBackend"

    ALPACA_KEY_ID = values.Value("", environ_prefix=None)
    ALPACA_SECRET_KEY = values.Value("", environ_prefix=None)
    ALPACA_BASE_URL = values.Value(
        "https://paper-api.alpaca.markets", environ_prefix=None
    )

    OPENAI_MODEL = values.Value("gpt-4o-mini", environ_prefix=None)


class Development(Common):
    DEBUG = values.BooleanValue(True, environ_prefix=None)
    ALLOWED_HOSTS = values.ListValue(
        [
            "*",
        ]
    )


class Staging(Common):
    ALLOWED_HOSTS = values.ListValue(["localhost", "0.0.0.0", "scorpyourllc.com"])


class Production(Common):
    pass
