# Generated by Django 6.0 on 2025-12-25 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tearsheet_pdf_path",
                    models.CharField(
                        help_text="Path to generated tear sheet PDF", max_length=255
                    ),
                ),
                (
                    "commentary_md_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to AI-generated commentary (Markdown)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "commentary_pdf_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("llm_model", models.CharField(blank=True, max_length=64, null=True)),
                ("prompt_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("inputs_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="performance.monthlysnapshot",
                    ),
                ),
            ],
        ),
    ]
