# Generated by Django 6.0 on 2025-12-27 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "performance",
            "0003_remove_monthlyreportartifact_uq_monthly_report_fund_year_month_and_more",
        ),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated monthly commentary (Markdown)",
                        null=True,
                    ),
                ),
                (
                    "html_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/html/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/pdf/"
                    ),
                ),
                (
                    "chart_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/monthly/charts/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_artifact",
                        to="performance.monthlysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
