# Generated by Django 6.0 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable fund name", max_length=128
                    ),
                ),
                (
                    "strategy_code",
                    models.CharField(
                        help_text="Internal strategy identifier (e.g. ETF_MOM_V1)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("inception_date", models.DateField()),
                (
                    "custodian",
                    models.CharField(
                        choices=[("ALPACA", "Alpaca"), ("IBKR", "Interactive Brokers")],
                        help_text="Trading custodian / broker",
                        max_length=16,
                    ),
                ),
                (
                    "custodian_account_id",
                    models.CharField(
                        help_text="Broker-specific account identifier", max_length=128
                    ),
                ),
                (
                    "custodian_account_masked",
                    models.CharField(
                        blank=True,
                        help_text="Masked broker account (e.g. ****1234)",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("base_currency", models.CharField(default="USD", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["strategy_code"], name="funds_fund_strateg_a5045a_idx"
                    ),
                    models.Index(
                        fields=["custodian", "status"],
                        name="funds_fund_custodi_70754a_idx",
                    ),
                ],
            },
        ),
    ]
