# Generated by Django 6.0 on 2026-01-10 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        db_index=True,
                        default="operations_db",
                        help_text="Logical backup target (e.g., operations_db).",
                        max_length=64,
                    ),
                ),
                (
                    "db_path",
                    models.CharField(default="/data/operations.db", max_length=512),
                ),
                ("bucket", models.CharField(blank=True, default="", max_length=128)),
                ("region", models.CharField(blank=True, default="", max_length=64)),
                ("endpoint", models.CharField(blank=True, default="", max_length=256)),
                (
                    "key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "prefix",
                    models.CharField(default="backups/operations", max_length=256),
                ),
                ("filename", models.CharField(default="operations", max_length=128)),
                ("max_days", models.PositiveIntegerField(default=30)),
                ("gzip_enabled", models.BooleanField(default=True)),
                ("acl", models.CharField(default="private", max_length=32)),
                ("dry_run", models.BooleanField(default=False)),
                ("uploaded_bytes", models.BigIntegerField(default=0)),
                ("compressed", models.BooleanField(default=False)),
                ("deleted_old", models.IntegerField(default=0)),
                ("kept", models.IntegerField(default=0)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
            ],
        ),
    ]
